stages:
  - deploy

deploy:
  stage: deploy
  variables: 
    GIT_CLONE_PATH: $CI_BUILDS_DIR/micro_crossmessages
  tags: 
    - micro_crossmessages
  script:
    - docker compose exec -T php composer install && docker compose exec -T php php bin/console doctrine:migrations:migrate --no-interaction &&docker compose exec -T php php bin/console cache:clear
  environment:
    name: micro_crossmessages
    url: http://crs1vqd7feyzj3vmeg6kurolp20nbf.ru
  only:
    - main
